// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uukhadrnmchfpxkcsuxz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV1a2hhZHJubWNoZnB4a2NzdXh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MDIyODIsImV4cCI6MjA3MjM3ODI4Mn0.9G_oE6Dczkx9q-ZBBQtOkm37ckdPIum22dRgalt-AEI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});